from django.contrib import admin
from .models import Modules, ContentTypes, Content, CompletedContent, Quiz, QuizScore, QuestionTypes, Question, Choice, TFAnswer, MCAnswer, SAAnswer, TFUserAnswer, MCUserAnswer, SAUserAnswer
admin.site.register(Modules)
admin.site.register(ContentTypes)
admin.site.register(Content)
admin.site.register(CompletedContent)
admin.site.register(Quiz)
admin.site.register(QuizScore)
admin.site.register(QuestionTypes)
admin.site.register(Question)
admin.site.register(Choice)
admin.site.register(TFAnswer)
admin.site.register(MCAnswer)
admin.site.register(SAAnswer)
admin.site.register(TFUserAnswer)
admin.site.register(MCUserAnswer)
admin.site.register(SAUserAnswer)
