# Generated by Django 2.2.4 on 2019-11-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('RN', 'Nurse (RN)'), ('LV', 'Nurse (LVN)'), ('HA', 'Hospice Aide'), ('SP', 'Spiritual Care Provider'), ('SW', 'Social Worker'), ('OS', 'Office Staff')], default='OS', max_length=2),
        ),
    ]
