# Generated by Django 2.2.4 on 2019-11-21 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Role')),
            ],
        ),
        migrations.CreateModel(
            name='MCAnswer',
            fields=[
                ('answer', models.CharField(choices=[('a', 'First Choice'), ('b', 'Second Choice'), ('c', 'Third Choice'), ('d', 'Fourth Choice'), ('e', 'None')], default='e', max_length=1)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.Question')),
                ('choice1', models.CharField(default='', max_length=100)),
                ('choice2', models.CharField(default='', max_length=100)),
                ('choice3', models.CharField(default='', max_length=100)),
                ('choice4', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.Question')),
                ('type', models.CharField(choices=[('TF', 'TrueFalse'), ('SA', 'ShortAnswer'), ('MC', 'MultipleChoice')], default='TF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='QuizType',
            fields=[
                ('quiz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.Quiz')),
                ('type', models.CharField(choices=[('VD', 'Video'), ('HD', 'Handout'), ('SL', 'Slides')], default='VD', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='SAAnswer',
            fields=[
                ('answer', models.TextField(default='')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TFAnswer',
            fields=[
                ('answer', models.BooleanField(default=False)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('module', models.IntegerField()),
                ('url', models.URLField(default='')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Role')),
            ],
        ),
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('signed_date', models.DateTimeField(auto_now=True)),
                ('related_quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Quiz')),
                ('signed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz'),
        ),
        migrations.CreateModel(
            name='CompletedSlides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now=True)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Slide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
