# Generated by Django 2.2.4 on 2020-01-23 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_answer', models.CharField(blank=True, max_length=1, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='SAUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_answer', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Question')),
            ],
        ),
        migrations.CreateModel(
            name='TFUserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tf_answer', models.BooleanField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='quiz_score',
        ),
        migrations.RemoveField(
            model_name='usermcanswer',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='usersaanswer',
            name='user_answer',
        ),
        migrations.RemoveField(
            model_name='usertfanswer',
            name='user_answer',
        ),
        migrations.AlterModelOptions(
            name='completedcontent',
            options={'ordering': ['-completed_at']},
        ),
        migrations.AlterModelOptions(
            name='quizscore',
            options={'ordering': ['-signed_date']},
        ),
        migrations.RemoveField(
            model_name='mcanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='saanswer',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='tfanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='mcanswer',
            name='question',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='saanswer',
            name='question',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='tfanswer',
            name='question',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.Question'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='UserAnswer',
        ),
        migrations.DeleteModel(
            name='UserMCAnswer',
        ),
        migrations.DeleteModel(
            name='UserSAAnswer',
        ),
        migrations.DeleteModel(
            name='UserTFAnswer',
        ),
        migrations.AddField(
            model_name='tfuseranswer',
            name='quiz_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizScore'),
        ),
        migrations.AddField(
            model_name='sauseranswer',
            name='quiz_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizScore'),
        ),
        migrations.AddField(
            model_name='mcuseranswer',
            name='quiz_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizScore'),
        ),
    ]
