# Generated by Django 2.2.4 on 2019-11-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='url_value',
            field=models.CharField(default='', max_length=100),
        ),
    ]
