# Generated by Django 2.2.4 on 2019-12-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizscore',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
