# Generated by Django 2.2.4 on 2019-12-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='group',
        ),
        migrations.AddField(
            model_name='quiz',
            name='group',
            field=models.ManyToManyField(to='users.Role'),
        ),
    ]
