# Generated by Django 2.2.4 on 2019-11-19 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20191119_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcanswer',
            name='answer',
            field=models.CharField(choices=[('a', 'First choice'), ('b', 'Second choice'), ('c', 'Third choice'), ('d', 'Fourth choice'), ('e', 'None')], default='e', max_length=1),
        ),
        migrations.AddField(
            model_name='saanswer',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='tfanswer',
            name='answer',
            field=models.BooleanField(default=False),
        ),
    ]
