# Generated by Django 2.2.4 on 2019-12-02 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('quiz', '0002_auto_20191202_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='group',
        ),
        migrations.AddField(
            model_name='slide',
            name='group',
            field=models.ManyToManyField(to='users.Role'),
        ),
    ]
