# Generated by Django 2.2.4 on 2019-09-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190920_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookuptableslideuser',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lookuptableslideuser',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
