# Generated by Django 2.2.4 on 2020-01-24 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200123_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcanswer',
            old_name='mc_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='mcuseranswer',
            old_name='mc_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='saanswer',
            old_name='sa_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='sauseranswer',
            old_name='sa_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='tfanswer',
            old_name='tf_answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='tfuseranswer',
            old_name='tf_answer',
            new_name='answer',
        ),
    ]
