# Generated by Django 2.2.4 on 2019-12-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizscore_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
