# Generated by Django 2.2.4 on 2019-11-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_url_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcanswer',
            name='choice1',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mcanswer',
            name='choice2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mcanswer',
            name='choice3',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mcanswer',
            name='choice4',
            field=models.TextField(default=''),
        ),
    ]
