# Generated by Django 2.2.4 on 2019-12-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20191202_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='multiple_choice',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='short_answer',
            field=models.TextField(null=True),
        ),
    ]
