# Generated by Django 2.2.4 on 2019-11-19 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20191119_1328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcanswer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='saanswer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tfanswer',
            name='id',
        ),
        migrations.AlterField(
            model_name='mcanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.Question'),
        ),
        migrations.AlterField(
            model_name='saanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.Question'),
        ),
        migrations.AlterField(
            model_name='tfanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quiz.Question'),
        ),
    ]
