# Generated by Django 2.2.4 on 2019-12-17 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20191211_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('true_or_false', models.BooleanField(blank=True, null=True)),
                ('multiple_choice', models.CharField(blank=True, max_length=1, null=True)),
                ('short_answer', models.TextField(blank=True, null=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Question')),
                ('quiz_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuizScore')),
            ],
        ),
    ]
