# Generated by Django 2.2.4 on 2020-01-27 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20200123_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='content',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='quiz.Content'),
        ),
    ]
