# Generated by Django 2.2.4 on 2019-11-20 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20191119_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
