# Generated by Django 2.2.4 on 2019-12-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20191202_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='multiple_choice',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='short_answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='true_or_false',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
