# Generated by Django 2.2.4 on 2019-10-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190926_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('VD', 'Video'), ('HD', 'Handout'), ('SL', 'Slides')], default='VD', max_length=2),
        ),
    ]
