# Generated by Django 2.2.4 on 2019-10-16 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizscore',
            name='related_quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.Quiz'),
        ),
    ]
