# Generated by Django 2.2.4 on 2019-12-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20191204_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='num_questions',
            field=models.BooleanField(default=0),
        ),
    ]
