# Generated by Django 2.2.4 on 2019-12-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quiz_num_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='num_questions',
            field=models.IntegerField(default=0),
        ),
    ]
