# Generated by Django 2.2.4 on 2019-11-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_mcanswer_saanswer_tfanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user_role',
            field=models.CharField(choices=[('ALL', 'All Staff'), ('CLN', 'Clinical Staff'), ('NUR', 'Nurses')], default='ALL', max_length=3),
        ),
        migrations.AddField(
            model_name='slide',
            name='user_role',
            field=models.CharField(choices=[('ALL', 'All Staff'), ('CLN', 'Clinical Staff'), ('NUR', 'Nurses')], default='ALL', max_length=3),
        ),
    ]
