# Generated by Django 2.2.4 on 2019-12-04 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0008_auto_20191204_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_reviewed',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='quizscore',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizscore',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quizscore',
            name='signed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_signed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
