# Generated by Django 2.2.4 on 2019-12-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20191204_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='review_required',
            field=models.BooleanField(default=False),
        ),
    ]
